packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.100.14
  "@types/node": ^24.12.2
  "@types/react": ^19.2.16
  "@types/react-dom": ^19.2.3
  "@vanilla-extract/vite-plugin": ^5.2.2
  autoprefixer: ^10.5.0
  jsdom: ^29.1.1
  oxfmt: ^0.53.0
  oxlint: ^1.68.0
  postcss: ^8.5.15
  postcss-prefix-selector: ^2.1.1
  react: ^19.2.7
  react-dom: ^19.2.7
  tsdown: ^0.22.1
  typescript: ^6.0.3
  viem: ^2.52.0
  vite: ^8.0.16
  vitest: ^4.1.8
  wagmi: ^3.6.16

overrides:
  "@types/react": "catalog:"
  "@types/react-dom": "catalog:"
  "@types/node": "catalog:"
  "react": "catalog:"
  "react-dom": "catalog:"
  "typescript": "catalog:"
  "abitype>zod": "-"
  "react-native": "-"
  "@paulmillr/qr": "npm:qr@^0.5.5"

catalogMode: manual
strictDepBuilds: false

allowBuilds:
  "@reown/appkit": false
  bufferutil: false
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  utf-8-validate: false
